// <auto-generated />
using System;
using EmotionDetectionSystem.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmotionDetectionSystem.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmotionDetectionSystem.DomainLayer.objects.EmotionData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EnrollmentSummaryLessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EnrollmentSummaryLessonId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EnrollmentSummaryStudentId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EnrollmentSummaryStudentId1")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("WinningEmotion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentSummaryLessonId", "EnrollmentSummaryStudentId");

                    b.HasIndex("EnrollmentSummaryLessonId1", "EnrollmentSummaryStudentId1");

                    b.ToTable("EmotionData");
                });

            modelBuilder.Entity("EmotionDetectionSystem.DomainLayer.objects.Lesson", b =>
                {
                    b.Property<string>("LessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EntryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LessonId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("EmotionDetectionSystem.DomainLayer.objects.User", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EnrollmentSummary", b =>
                {
                    b.Property<string>("LessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherApproach")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("LessonId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("EnrollmentSummary");
                });

            modelBuilder.Entity("EmotionDetectionSystem.DomainLayer.objects.Student", b =>
                {
                    b.HasBaseType("EmotionDetectionSystem.DomainLayer.objects.User");

                    b.ToTable("User");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("EmotionDetectionSystem.DomainLayer.objects.Teacher", b =>
                {
                    b.HasBaseType("EmotionDetectionSystem.DomainLayer.objects.User");

                    b.ToTable("User");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("EmotionDetectionSystem.DomainLayer.objects.EmotionData", b =>
                {
                    b.HasOne("EnrollmentSummary", null)
                        .WithMany("EmotionData")
                        .HasForeignKey("EnrollmentSummaryLessonId", "EnrollmentSummaryStudentId");

                    b.HasOne("EnrollmentSummary", null)
                        .WithMany("NegativeEmotionData")
                        .HasForeignKey("EnrollmentSummaryLessonId1", "EnrollmentSummaryStudentId1");
                });

            modelBuilder.Entity("EmotionDetectionSystem.DomainLayer.objects.Lesson", b =>
                {
                    b.HasOne("EmotionDetectionSystem.DomainLayer.objects.Teacher", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EnrollmentSummary", b =>
                {
                    b.HasOne("EmotionDetectionSystem.DomainLayer.objects.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmotionDetectionSystem.DomainLayer.objects.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EnrollmentSummary", b =>
                {
                    b.Navigation("EmotionData");

                    b.Navigation("NegativeEmotionData");
                });

            modelBuilder.Entity("EmotionDetectionSystem.DomainLayer.objects.Teacher", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
